apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: uber

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: thesanketpawar/uber-backend:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 4000

        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_URI
