apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: uber

type: Opaque

data:
  NODE_ENV:
  PORT:
  MONGO_URI:
  JWT_SECRET:
  MAILTRAP_HOST:
  MAILTRAP_PORT:
  MAILTRAP_USER:
  MAILTRAP_PASS:
  LOCATIONIQ_API_KEY: